specVersion: 0.2.0
description: ''
repository: ''
schema: 
  file: ./schema.graphql
network:
  endpoint: 'wss://moonriver.api.onfinality.io/public-ws'
  genesisHash: '0x401a1f9dca3da46f5c4091016c8a2f26dcea05865116b286f60f668207d1474b'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1  # 7560558   7560585 7560724
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        # - handler: handleEvent
        #   kind: substrate/EventHandler
      #handlers:
      #  - handler: handleTransfer
      #    kind: substrate/EventHandler
      #    filter:
      #      module: balances
      #      method: Transfer
