specVersion: 0.2.0
description: 'Moonriver balance and activities indexer'
repository: 'https://github.com/web3go-xyz/moonbeam-balance-indexer.git@moonriver-balance-indexer'
schema: 
  file: ./schema.graphql
network:
  endpoint: 'wss://moonriver.api.onfinality.io/public-ws'
  genesisHash: '0x401a1f9dca3da46f5c4091016c8a2f26dcea05865116b286f60f668207d1474b'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1052242 # => runtime 1001

    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        # - handler: handleEvent
        #   kind: substrate/EventHandler

